---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <my-cluster>
  region: <us-west-2>
  version: '1.18'

iam:
  withOIDC: true   

managedNodeGroups:
  - name: <linux-ng>
    instanceType: <m5.large>
    minSize: <2>